### ISSUE TITLE
So do i go to jail?

### ISSUE THREAD

**Issue by amanuel2** [khanh2003/Hoc462#3]
I just used ur code.. what's happens now?

**Comment by khanh2003** [comment]
My code is in my Mac.
When I consumed the tutorial, I will publish it, soon.

**Comment by amanuel2** [comment]
You said you will go to jail If you use your code  in README .. I just did

**Comment by khanh2003** [comment]
LOL. Let's go back to Stack Exchange.
Locking this for now.
